name: Create GitHub Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run quality checks
        run: |
          bunx eslint .
          bun run format:check
          bunx tsc --noEmit

      - name: Build
        run: bun run build

      - name: Determine version and create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(node -p "require('./package.json').version")

          if git tag --list | grep -q "^v$VERSION$"; then
            echo "Tag v$VERSION already exists, skipping release creation."
            exit 0
          fi

          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag "v$VERSION"
          git push origin "v$VERSION"

          gh release create "v$VERSION" \
            --title "v$VERSION" \
            --generate-notes \
            --latest \
            ./dist/agent-exporter
